export type BULB_ACTION_TYPE = 'EMPTY_BULB' | 'REMOVE_BULB' | 'SELECT_BULB';

export const ADD_BULB = 'ADD_BULB';
export const TRANSFER_LIQUID = 'TRANSFER_LIQUID';
export const EMPTY_BULB = 'EMPTY_BULB' as BULB_ACTION_TYPE;
export const REMOVE_BULB = 'REMOVE_BULB' as BULB_ACTION_TYPE;
export const REMOVE_BULB_SELECTION = 'REMOVE_BULB_SELECTION';
export const SELECT_BULB = 'SELECT_BULB' as BULB_ACTION_TYPE;
